### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by yoyo34556** [IouJenLiu/AFK#1]
Hello, I am a student in Japan.
Your research is very interesting.
I actually tried to run your prepared code , but
I got the following error
Is there any solution for this?

"Function `rng.randint(low, [high, size, dtype])` is marked as deprecated "
-= Games #[799572887, 1811408612, 1493662463, 1791150409, 2078953035] =-
Traceback (most recent call last):
  File "test_cooking_afk_batch.py", line 136, in <module>
    main()
  File "test_cooking_afk_batch.py", line 117, in main
    assert word in "{} {} {}".format(obs_, inv_, desc_), word
AssertionError: cook
Exception ignored in: <function AsyncBatchEnv.__del__ at 0x7f2029906e60>
Traceback (most recent call last):
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 196, in __del__
    self.close()
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 189, in close
    env.call("close")
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 63, in call
    self._pipe.send(("call", method, args))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function _ChildEnv.__del__ at 0x7f20299069e0>
Traceback (most recent call last):
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 87, in __del__
    self.call_sync("close")
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 75, in call_sync
    self.call(*args)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 63, in call
    self._pipe.send(("call", method, args))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function _ChildEnv.__del__ at 0x7f20299069e0>
Traceback (most recent call last):
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 87, in __del__
    self.call_sync("close")
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 75, in call_sync
    self.call(*args)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 63, in call
    self._pipe.send(("call", method, args))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function _ChildEnv.__del__ at 0x7f20299069e0>
Traceback (most recent call last):
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 87, in __del__
    self.call_sync("close")
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 75, in call_sync
    self.call(*args)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 63, in call
    self._pipe.send(("call", method, args))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function _ChildEnv.__del__ at 0x7f20299069e0>
Traceback (most recent call last):
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 87, in __del__
    self.call_sync("close")
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 75, in call_sync
    self.call(*args)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 63, in call
    self._pipe.send(("call", method, args))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function _ChildEnv.__del__ at 0x7f20299069e0>
Traceback (most recent call last):
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 87, in __del__
    self.call_sync("close")
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 75, in call_sync
    self.call(*args)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/site-packages/textworld/envs/batch/batch_env.py", line 63, in call
    self._pipe.send(("call", method, args))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/yoneda/anaconda3/envs/afk/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by MarcCote** [comment]
Thanks for reporting. It seems there was an assertion error in the textworld code. I'll have a look at this issue today. (tagging @xingdi-eric-yuan and @IouJenLiu for visibility).
